// Generated by scripts/generate-internal-paths.mjs — do not edit by hand.
// Source of truth is the `visibility: internal` frontmatter field; re-run
// the generator (wired into `pnpm build`) after changing any page's visibility.
export const INTERNAL_PATHS: readonly string[] = [
  "/deployment/agentgateway/",
  "/deployment/overview/",
  "/mzizi-tools/a2a/",
  "/mzizi-tools/dna-helix/",
  "/mzizi-tools/overview/",
  "/mzizi-tools/registry-health/",
  "/tools/"
];
